RECEPTIONIST = 'Receptionist'
DOCTOR = 'Doctor'
NURSE = 'Nurse'
STUDENT_CLINICIAN = 'Student Clinician'

ROLES = (
    (RECEPTIONIST, RECEPTIONIST),
    (DOCTOR, DOCTOR),
    (NURSE, NURSE),
    (STUDENT_CLINICIAN, STUDENT_CLINICIAN)
)