# Generated by Django 3.2 on 2022-02-25 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220225_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ward',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
