# Generated by Django 3.2 on 2022-02-26 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_user_roles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='roles',
            new_name='role',
        ),
    ]
