# Generated by Django 3.2 on 2022-02-27 20:14

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_referral_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='description',
            field=models.TextField(max_length=400, validators=[django.core.validators.MinLengthValidator(20)]),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='end_datetime',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2022, 2, 27, 20, 14, 34, 465392, tzinfo=utc))]),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='start_datetime',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2022, 2, 27, 20, 14, 34, 465392, tzinfo=utc))]),
        ),
    ]
