# Generated by Django 3.2 on 2022-03-10 11:51

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20220306_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date(2022, 3, 10))]),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='end_datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='start_datetime',
            field=models.DateTimeField(),
        ),
    ]
